# Generated by Django 4.0.4 on 2022-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_no', models.CharField(max_length=5)),
                ('driver', models.CharField(max_length=50)),
                ('total_students', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
